name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限设置
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        
    - name: Install wasm-pack
      uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        use-tool-cache: true
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build TailwindCSS
      run: npx tailwindcss -i ./styles/input.css -o ./public/styles/output.css

    - name: List public directory before build
      run: ls -R public
      
    - name: Build WebAssembly
      run: wasm-pack build --target web --out-dir public/pkg

    - name: List public directory after build
      run: ls -R public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
        publish_branch: gh-pages

    - name: List public directory stop deploy
      run: ls -R public