name: Test Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        
    - name: Install wasm-pack
      uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        use-tool-cache: true
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check Rust code
      run: cargo check
      
    - name: Build TailwindCSS
      run: npx tailwindcss -i ./styles/input.css -o ./public/styles/output.css
      
    - name: Build WebAssembly
      run: wasm-pack build --target web
      
    - name: Verify build output
      run: |
        ls -la pkg/
        ls -la public/styles/ 